/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.company.resume.panel;

import dao.inter.NationalityDaoInter;
import entity.Nationality;
import entity.User;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import main.Context;
import static com.company.resume.main.Config.loggedInUser;

/**
 *
 * @author USER
 */
public class DetailsPanell extends javax.swing.JPanel {
    private NationalityDaoInter nationalityDao = Context.instanceNationalityDao();
    private SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");


    /**
     * Creates new form DetailsPanell
     */
    public DetailsPanell() {
        initComponents();
        this.fillWindow();
    }
    
    public void fillWindow(){
        List<Nationality> list = nationalityDao.getAllCountryName();
        for(Nationality nationality:list){
            comBoxBirthplace.addItem(nationality);
            comBoxNationality.addItem(nationality);
        }
    }
       public void fillUserComponents(){
        txtAddress.setText(loggedInUser.getAddress());
        txtNumber.setText(loggedInUser.getPhone());
        txtEmail.setText(loggedInUser.getEmail());
        Date date = loggedInUser.getBirthdate();
        txtBirthdate.setText(sdf.format(date));
        comBoxBirthplace.setSelectedItem(loggedInUser.getBirthplace());
        comBoxNationality.setSelectedItem(loggedInUser.getNationality());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumber = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblBirthdate = new javax.swing.JLabel();
        lblNationality = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtBirthdate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comBoxBirthplace = new javax.swing.JComboBox<>();
        lblAdress = new javax.swing.JLabel();
        comBoxNationality = new javax.swing.JComboBox<>();

        lblNumber.setText("Phone Number");

        lblEmail.setText("E-mail");

        lblBirthdate.setText("Birthdate");

        lblNationality.setText("Nationality");

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        jLabel1.setText("Birthplace");

        comBoxBirthplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxBirthplaceActionPerformed(evt);
            }
        });

        lblAdress.setText("Address");

        comBoxNationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxNationalityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(lblNationality)
                    .addComponent(lblBirthdate)
                    .addComponent(lblEmail)
                    .addComponent(lblNumber)
                    .addComponent(lblAdress))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAddress)
                    .addComponent(txtNumber)
                    .addComponent(txtBirthdate)
                    .addComponent(txtEmail)
                    .addComponent(comBoxBirthplace, 0, 172, Short.MAX_VALUE)
                    .addComponent(comBoxNationality, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumber)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBirthdate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comBoxBirthplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNationality)
                    .addComponent(comBoxNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void fillUser(User user){
         try{
            String address = txtAddress.getText();
            String number = txtNumber.getText();
            String email = txtEmail.getText();
            java.sql.Date birthdate = new java.sql.Date(sdf.parse(txtBirthdate.getText()).getTime());
            Nationality country = (Nationality) comBoxBirthplace.getSelectedItem();
            Nationality nationality = (Nationality) comBoxNationality.getSelectedItem();

            user.setAddress(address);
            user.setPhone(number);
            user.setEmail(email);
            user.setBirthdate(birthdate);
            user.setBirthplace(country);
            user.setNationality(nationality);

        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    
    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void comBoxBirthplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxBirthplaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxBirthplaceActionPerformed

    private void comBoxNationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxNationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxNationalityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Nationality> comBoxBirthplace;
    private javax.swing.JComboBox<Nationality> comBoxNationality;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblBirthdate;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNationality;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBirthdate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNumber;
    // End of variables declaration//GEN-END:variables
}
